version: '3.7'

services:
  jenkins-docker:
    image: docker:dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true
    ports:
      - "2376:2376"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    networks:
      jenkins:
        aliases:
          - docker

  jenkins-blueocean:
    build: .
    image: myjenkins-blueocean:2.346.3-1
    restart: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - jenkins

  sonatype-nexus3:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      jenkins:
        aliases:
          - nexus3

networks:
  jenkins:

volumes:
  jenkins-docker-certs:
  jenkins-data:
  nexus-data:

