version: '3.7'

services:
  jenkins-docker:
    hostname: docker
    image: docker:dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true
    ports:
      - "2376:2376"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    networks:
      - internal_access

  jenkins-blueocean:
    build: .
    image: myjenkins-blueocean:2.346.3-1
    restart: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - internal_access
      - external_access

  sonatype-nexus3:
    hostname: nexus3
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - internal_access
      - external_access

networks:
  internal_access:
    internal: true
  external_access:

volumes:
  jenkins-docker-certs:
    external: true
  jenkins-data:
    external: true
  nexus-data:
    external: true

