version: '3.7'

services:
  master:
    container_name: ansible-master
    build: ./master
    image: ansible-master
    ports:
      - 22:22
    networks:
      - ansible-net
    volumes:
      - inventory-vol:/etc/ansible

  node1:
    container_name: ansible-node1
    build: ./slave
    image: ansible-slave
    networks:
      - ansible-net

  node2:
    container_name: ansible-node2
    image: ansible-slave
    networks:
      - ansible-net
  
  node3:
    container_name: ansible-node3
    image: ansible-slave
    networks:
      - ansible-net

networks:
  ansible-net:

volumes:
  inventory-vol:
    external: true
