version: '3.7'

services:
  master:
    container_name: ansible-master
    build: ./master
    image: ansible-master
    ports:
      - 22:22
    networks:
      - internal_access
      - external_access

  slave1:
    container_name: ansible-slave
    build: ./slave
    image: ansible-slave
    networks:
      - internal_access

networks:
  internal_access:
    internal: true
  external_access:
